version: '2'

services:
  web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./web:/src
        - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
  php:
    image: php:fpm
    volumes:
      - ./web:/src
      - ./nginx/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
